#!/usr/bin/env sh

set -u

ROOT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)"
TARGET="$ROOT_DIR/setupPVPN.sh"
FAIL_COUNT=0
FAIL_LIST=""

add_fail() {
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_LIST="${FAIL_LIST}\n- $1"
}

assert_contains() {
    needle="$1"
    label="$2"
    if ! grep -Fq -- "$needle" "$TARGET"; then
        add_fail "$label"
    fi
}

if [ ! -f "$TARGET" ]; then
    add_fail "setupPVPN.sh not found at $TARGET"
else
    sh -n "$TARGET" || add_fail "setupPVPN.sh fails sh -n"
    assert_contains '"repair" "Repair ProtonVPN setup files and startup hooks"' "repair menu item missing"
    assert_contains 'run_repair_flow()' "run_repair_flow function missing"
    assert_contains 'run_uninstall_flow()' "run_uninstall_flow function missing"
    assert_contains "case \"\$ACTION\" in" "action case block missing"
    assert_contains 'repair)' "repair case option missing"
    assert_contains 'remove_startup_files' "startup cleanup function usage missing"
    assert_contains 'ensure_self_executable' "self auto-chmod invocation missing"
    assert_contains 'show_action_menu' "menu invocation missing"
    assert_contains 'parse_cli_args()' "CLI argument parser function missing"
    assert_contains 'validate_connect_preferences()' "connect mode validation function missing"
    assert_contains 'validate_split_tunnel_preferences()' "split tunnel validation function missing"
    assert_contains 'run_command_sanity_check()' "command sanity-check function missing"
    assert_contains 'run_status_flow()' "status flow function missing"
    assert_contains 'sanity_check_environment()' "sanity check function missing"
    assert_contains 'log_timestamp()' "persistent logging timestamp helper missing"
    assert_contains 'append_persistent_log()' "persistent logging append helper missing"
    assert_contains 'json_escape()' "json escape helper missing"
    assert_contains 'write_file_if_changed()' "idempotent file reconciliation function missing"
    assert_contains 'write_wrapper() {' "write_wrapper function missing"
    assert_contains 'safe_remove_path()' "safe remove helper missing"
    assert_contains 'for dep in grep mktemp cmp dirname date mkdir sed tr cut; do' "sanity core dependency check list missing"
    assert_contains 'Idempotent run: no file changes needed for' "idempotent no-change log message missing"
    assert_contains 'Refusing to remove managed setup script:' "setup script removal protection warning missing"
    assert_contains '--non-interactive|-n' "non-interactive option parsing missing"
    assert_contains 'CONNECT_MODE="default"' "connect mode default variable missing"
    assert_contains 'CONNECT_COUNTRY=""' "connect country variable missing"
    assert_contains 'CONNECT_RETRY_COUNT="1"' "connect retry count default variable missing"
    assert_contains 'CONNECT_RETRY_DELAY="5"' "connect retry delay default variable missing"
    assert_contains 'SPLIT_TUNNEL_EXCLUDE_IPS=""' "split tunnel exclude IPs variable missing"
    assert_contains 'SPLIT_TUNNEL_EXCLUDE_CIDRS=""' "split tunnel exclude CIDRs variable missing"
    assert_contains 'STATE_LOG_DIR=' "state log directory variable missing"
    assert_contains 'LOG_FILE=' "persistent log file variable missing"
    assert_contains 'SANITY_ONLY=0' "sanity-only mode state variable missing"
    assert_contains 'NON_INTERACTIVE=0' "non-interactive mode state variable missing"
    assert_contains 'Running non-interactive action:' "non-interactive execution branch missing"
    assert_contains 'DRY_RUN=0' "dry-run state variable missing"
    assert_contains 'ASSUME_YES=0' "--yes state variable missing"
    assert_contains 'FORCE_DISABLE_KILL_SWITCH=0' "force-disable-kill-switch state variable missing"
    assert_contains 'UNINSTALL_PACKAGES_DECISION="no"' "uninstall decision tracking variable missing"
    assert_contains 'PURGE_CONFIG_DECISION="no"' "purge config decision tracking variable missing"
    assert_contains 'KILL_SWITCH_WAS_ENABLED=0' "kill-switch enabled state variable missing"
    assert_contains 'KILL_SWITCH_DISABLED_FOR_UNINSTALL=0' "kill-switch disable state variable missing"
    assert_contains '--dry-run)' "dry-run option parsing missing"
    assert_contains '--yes|-y)' "--yes option parsing missing"
    assert_contains '--force-disable-kill-switch)' "force-disable-kill-switch option parsing missing"
    assert_contains '--connect-mode)' "connect-mode option parsing missing"
    assert_contains '--country-code)' "country-code option parsing missing"
    assert_contains '--connect-retry)' "connect-retry option parsing missing"
    assert_contains '--connect-retry-delay)' "connect-retry-delay option parsing missing"
    assert_contains '--sanity-check)' "sanity-check option parsing missing"
    assert_contains '--status)' "status option parsing missing"
    assert_contains '--exclude-ip)' "exclude-ip option parsing missing"
    assert_contains '--exclude-cidr)' "exclude-cidr option parsing missing"
    assert_contains 'install|repair|status|uninstall|quit|sanity-check' "non-interactive status/sanity action option missing"
    assert_contains 'Missing value for --connect-mode. Use default|fastest|country.' "connect-mode missing value guard missing"
    assert_contains 'Missing value for --country-code. Use a two-letter code like US.' "country-code missing value guard missing"
    assert_contains 'Missing value for --connect-retry. Use integer >= 1.' "connect-retry missing value guard missing"
    assert_contains 'Missing value for --connect-retry-delay. Use integer >= 0.' "connect-retry-delay missing value guard missing"
    assert_contains 'Missing value for --exclude-ip. Use IPv4 address.' "exclude-ip missing value guard missing"
    assert_contains 'Missing value for --exclude-cidr. Use CIDR like 192.168.1.0/24.' "exclude-cidr missing value guard missing"
    assert_contains "CONNECT_MODE=\"\$1\"" "connect-mode assignment parsing missing"
    assert_contains "CONNECT_COUNTRY=\"\$1\"" "country-code assignment parsing missing"
    assert_contains "CONNECT_RETRY_COUNT=\"\$1\"" "connect-retry assignment parsing missing"
    assert_contains "CONNECT_RETRY_DELAY=\"\$1\"" "connect-retry-delay assignment parsing missing"
    assert_contains "SPLIT_TUNNEL_EXCLUDE_IPS=\"\${SPLIT_TUNNEL_EXCLUDE_IPS},\$1\"" "exclude-ip append parsing missing"
    assert_contains "SPLIT_TUNNEL_EXCLUDE_CIDRS=\"\${SPLIT_TUNNEL_EXCLUDE_CIDRS},\$1\"" "exclude-cidr append parsing missing"
    assert_contains 'ACTION="sanity-check"' "sanity-check action assignment missing"
    assert_contains '--connect-mode country requires --country-code <CC>.' "country mode requires country-code guard missing"
    assert_contains "Country code provided but connect mode is \$CONNECT_MODE; country code will be ignored." "country-code ignored warning missing"
    assert_contains '[A-Z][A-Z])' "country-code format validation missing"
    assert_contains "tr '[:lower:]' '[:upper:]'" "country-code normalization missing"
    assert_contains "Invalid --connect-retry value: \$CONNECT_RETRY_COUNT (expected integer >= 1)." "connect-retry validation guard missing"
    assert_contains "Invalid --connect-retry-delay value: \$CONNECT_RETRY_DELAY (expected integer >= 0)." "connect-retry-delay validation guard missing"
    assert_contains "Invalid --exclude-ip value: \$exclude_ip" "exclude-ip validation guard missing"
    assert_contains "Invalid --exclude-cidr value: \$exclude_cidr" "exclude-cidr validation guard missing"
    assert_contains 'Dry-run mode enabled. No changes will be written.' "dry-run execution notice missing"
    assert_contains 'Auto-confirm enabled with --yes; uninstalling ProtonVPN CLI packages.' "--yes uninstall auto-confirm message missing"
    assert_contains 'Force-disable-kill-switch flag enabled; attempting kill switch disable before uninstall.' "force disable kill-switch behavior message missing"
    assert_contains 'Non-interactive uninstall without --yes: keeping ProtonVPN CLI packages.' "non-interactive uninstall safe default message missing"
    assert_contains 'CI SUMMARY: would uninstall packages: %s' "dry-run uninstall CI summary line missing"
    assert_contains 'CI SUMMARY: uninstall packages: %s' "uninstall CI summary line missing"
    assert_contains 'CI_JSON: {"would_uninstall_packages":"%s"}' "dry-run uninstall CI_JSON line missing"
    assert_contains 'CI_JSON: {"uninstall_packages":"%s"}' "uninstall CI_JSON line missing"
    assert_contains 'CI SUMMARY: would purge configs: %s' "dry-run purge config CI summary line missing"
    assert_contains 'CI SUMMARY: purge configs: %s' "purge config CI summary line missing"
    assert_contains 'would_purge_configs' "dry-run purge config CI_JSON line missing"
    assert_contains 'purge_configs' "purge config CI_JSON line missing"
    assert_contains 'CI_JSON: {"action":"%s","dry_run":%s,"non_interactive":%s,"assume_yes":%s,"force_disable_kill_switch":%s,"uninstall_packages_decision":"%s","kill_switch_was_enabled":%s,"kill_switch_disabled_for_uninstall":%s}' "consolidated uninstall CI_JSON line missing"
    assert_contains 'exit_handler() {' "global exit telemetry handler missing"
    assert_contains 'trap exit_handler EXIT' "global exit telemetry trap missing"
    assert_contains 'success' "global CI success telemetry field missing"
    assert_contains 'purge_config_decision' "global purge config telemetry field missing"
    assert_contains 'connect_mode' "global connect mode telemetry field missing"
    assert_contains 'connect_country' "global connect country telemetry field missing"
    assert_contains 'connect_retry_count' "global connect retry count telemetry field missing"
    assert_contains 'connect_retry_delay' "global connect retry delay telemetry field missing"
    assert_contains 'split_tunnel_exclude_ips' "global split tunnel IP telemetry field missing"
    assert_contains 'split_tunnel_exclude_cidrs' "global split tunnel CIDR telemetry field missing"
    assert_contains 'is_kill_switch_enabled()' "kill-switch status function missing"
    assert_contains 'disable_kill_switch_for_uninstall()' "kill-switch disable function missing"
    assert_contains 'ensure_kill_switch_safe_for_uninstall()' "kill-switch uninstall guard missing"
    assert_contains 'ensure_kill_switch_safe_for_uninstall' "kill-switch guard invocation missing"
    assert_contains 'prompt_purge_config_with_menu()' "purge config prompt function missing"
    assert_contains 'purge_user_protonvpn_data()' "purge user data function missing"
    assert_contains 'safe_remove_tree()' "safe recursive remove helper missing"
    assert_contains 'kill_switch_was_enabled' "kill-switch telemetry key missing"
    assert_contains 'kill_switch_disabled_for_uninstall' "kill-switch disable telemetry key missing"
    assert_contains 'Auto-confirm enabled with --yes; purging ProtonVPN user config/cache data.' "--yes purge config auto-confirm message missing"
    assert_contains 'Non-interactive uninstall without --yes: keeping ProtonVPN user config/cache data.' "non-interactive purge config safe default message missing"
    assert_contains "[dry-run] would reconcile file: \$target_file" "dry-run write-wrapper safeguard missing"
    assert_contains 'Description=ProtonVPN Auto-Connect Service' "systemd unit description upgrade missing"
    assert_contains 'Documentation=https://protonvpn.com/support/linux-cli/' "systemd documentation directive missing"
    assert_contains "Environment=\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\$HOME/.local/bin\"" "systemd PATH environment directive missing"
    assert_contains 'ExecStop=/usr/bin/env protonvpn disconnect' "systemd ExecStop disconnect directive missing"
    assert_contains 'TimeoutStartSec=60' "systemd timeout directive missing"
    assert_contains 'Restart=on-failure' "systemd restart policy directive missing"
    assert_contains 'RestartSec=10' "systemd restart delay directive missing"
    assert_contains 'StandardOutput=journal' "systemd journal stdout directive missing"
    assert_contains 'StandardError=journal' "systemd journal stderr directive missing"
    assert_contains 'ensure_apt_proton_repo()' "apt repository bootstrap function missing"
    assert_contains 'if ! sanity_check_environment; then' "sanity preflight invocation missing"
    assert_contains "write_file_if_changed \"\$UNIT\"" "idempotent systemd unit write usage missing"
    assert_contains "write_file_if_changed \"\$DESKTOP_ENTRY\"" "idempotent desktop entry write usage missing"
    assert_contains "write_file_if_changed \"\$WRAPPER\"" "idempotent wrapper write usage missing"
    assert_contains "[dry-run] would chmod +x \$WRAPPER" "dry-run wrapper chmod safeguard missing"
    assert_contains "safe_remove_path \"\$UNIT\"" "safe remove usage missing for unit file"
    assert_contains "safe_remove_path \"\$DESKTOP_ENTRY\"" "safe remove usage missing for desktop entry"
    assert_contains "safe_remove_path \"\$WRAPPER\"" "safe remove usage missing for wrapper script"
    assert_contains 'APT_REPO_DEB_URL=' "apt repository package URL constant missing"
    assert_contains 'Waiting for network connectivity...' "network wait message missing in wrapper"
    assert_contains "CONNECT_MODE=\"\$CONNECT_MODE\"" "wrapper connect mode injection missing"
    assert_contains "CONNECT_COUNTRY=\"\$CONNECT_COUNTRY\"" "wrapper connect country injection missing"
    assert_contains "CONNECT_RETRY_COUNT=\"\$CONNECT_RETRY_COUNT\"" "wrapper connect retry count injection missing"
    assert_contains "CONNECT_RETRY_DELAY=\"\$CONNECT_RETRY_DELAY\"" "wrapper connect retry delay injection missing"
    assert_contains "SPLIT_TUNNEL_EXCLUDE_IPS=\"\$SPLIT_TUNNEL_EXCLUDE_IPS\"" "wrapper split tunnel IP injection missing"
    assert_contains "SPLIT_TUNNEL_EXCLUDE_CIDRS=\"\$SPLIT_TUNNEL_EXCLUDE_CIDRS\"" "wrapper split tunnel CIDR injection missing"
    assert_contains 'apply_split_tunnel_exclusions() {' "wrapper split tunnel apply function missing"
    assert_contains 'split-tunnel-exclude-ip' "wrapper split tunnel IP config command missing"
    assert_contains 'split-tunnel-exclude-cidr' "wrapper split tunnel CIDR config command missing"
    assert_contains 'apply_split_tunnel_exclusions || true' "wrapper split tunnel apply invocation missing"
    assert_contains "case \"\\\$CONNECT_MODE\" in" "wrapper connect mode switch missing"
    assert_contains 'connect_once() { protonvpn connect --fastest; }' "wrapper fastest connect mode missing"
    assert_contains "protonvpn connect --cc \"\\\$CONNECT_COUNTRY\"" "wrapper country connect mode missing"
    assert_contains 'Unknown CONNECT_MODE: %s' "wrapper unknown mode fallback warning missing"
    assert_contains "while [ \"\\\$attempt\" -le \"\\\$CONNECT_RETRY_COUNT\" ]; do" "wrapper retry loop missing"
    assert_contains 'ProtonVPN connect attempt %s/%s failed; retrying in %ss.' "wrapper retry attempt message missing"
    assert_contains "sleep \"\\\$CONNECT_RETRY_DELAY\"" "wrapper retry delay sleep missing"
    assert_contains 'ProtonVPN connect failed after %s attempt(s).' "wrapper retry exhausted message missing"
    assert_contains 'ping -c 1 -W 1 1.1.1.1' "network readiness ping safeguard missing"
    assert_contains "ip route show default 2>/dev/null | grep -q '^default '" "network fallback default-route safeguard missing"
    assert_contains 'error() {' "error logging helper missing"
    assert_contains 'append_persistent_log "INFO"' "log persistent append missing for info"
    assert_contains 'append_persistent_log "WARN"' "log persistent append missing for warn"
    assert_contains 'append_persistent_log "ERROR"' "log persistent append missing for error"
    assert_contains 'run_command_sanity_check || return 1' "install flow sanity-check invocation missing"
    assert_contains 'validate_split_tunnel_preferences || return 1' "install flow split tunnel validation invocation missing"
    assert_contains 'Split tunneling exclusions configured:' "install flow split tunnel configuration log missing"
    assert_contains '"status" "Show ProtonVPN setup and health dashboard"' "status menu item missing"
    assert_contains 'STATUS_JSON:' "status JSON output missing"
    assert_contains 'sanity-check)' "sanity-check action dispatch missing"
    assert_contains 'run_command_sanity_check || SCRIPT_RESULT=1' "sanity-check action execution missing"
    assert_contains 'status)' "status action dispatch missing"
    assert_contains 'run_status_flow || SCRIPT_RESULT=1' "status action execution missing"
fi

if [ "$FAIL_COUNT" -gt 0 ]; then
    printf 'FAIL SUMMARY (%s)\n' "$FAIL_COUNT"
    printf '%b\n' "$FAIL_LIST"
    exit 1
fi

printf '[regression] PASS: setupPVPN.sh menu/flow guards validated.\n'
exit 0
